### PR TITLE
Untested: Add ZED support for LiveFeed

### PR DESCRIPTION
**Pull request by WillCurran**
Reviewer: Please make a new branch for me to merge this into, so I can test it before merging into aiming_zed. Thanks

### CODE REVIEW

**Comment by jeff-hykin** [comment]
The live camera feed stuff looks good

The parameters are a bit jank, but I think a bit part of that is the structure itself of only being able to pick one profile ("either Xavier or Laptop or Zed") I'll change the setup to something better

**Comment by jeff-hykin** [comment]
I'll make it look something like this, where we can combine multiple options 

```
default_parameters:
    stuff

options:
    zed:
        hardware:
             camera: zed
        aiming:
              height_or_whatever: 100
    xavier:
        hardware:
            board: Xavier
    development:
        mode: "development"
```

**Comment by WillCurran** [comment]
> I'll make it look something like this, where we can combine multiple options
> 
> ```
> default_parameters:
>     stuff
> 
> options:
>     zed:
>         hardware:
>              camera: zed
>         aiming:
>               height_or_whatever: 100
>     xavier:
>         hardware:
>             board: Xavier
>     development:
>         mode: "development"
> ```

Makes sense. Out of curiosity do you know if LiveFeed is going to stay in the end or if VideoStream is the way? I have code for both but I figured it was best to work in this aiming branch if this is where aiming team is working.

**Comment by jeff-hykin** [comment]
Oh I was accidentally substituting LiveVideo for VideoStream when I was looking at it.

Yeah we're gonna have to find a way to merge this with what's in master.

I think converting it to a VideoStream shouldn't be too bad, I'll try and see though

**Comment by WillCurran** [comment]
Yeah I'm happy to just change it to match VideoStream in master to avoid conflicts down the road if you think that's the best path forward.

**Comment by jeff-hykin** [comment]
Okay I completely redid the PARAMETERS system and streamlined it on the `dev` branch. It's now just called `config` and there's a ZED option inside the info.yaml

With the code merge situation, it'll probably be easiest to checkout the dev branch, and just fill out the existing `zed.py` file.

**Comment by WillCurran** [comment]
Awesome! So if I am following correctly, we will close this PR and I will make a new PR to dev. Then, that change eventually gets pulled into whatever branch aiming is working of.

**Comment by jeff-hykin** [comment]
Yup that should work 👍

**Comment by jeff-hykin** [comment]
Also, you don't need to make a fork. It's a lot easier to just make a branch on cv_main. Just call it `zed-wip` or something like that

**Comment by WillCurran** [comment]
I don't have write access to the repo, so unfortunately I can't do that. I would appreciate a collaborator invite if possible! I'll work in my fork until then

**Comment by jeff-hykin** [comment]
Lol sorry about that everyone should have access. We only really do PR's on master

**Pull request closed without merging**
